rules = [
  OrganizeImports,
  RedundantSyntax,
  RemoveUnused
]

OrganizeImports {
  targetDialect  = Scala3
  blankLines     = Auto
  expandRelative = true
  groupedImports = Merge
  groups         = [ "\"*\"" ]
  removeUnused   = true
}
