tado {
  api-auth            = "https://auth.tado.com"
  api-base            = "https://my.tado.com/api/v2"
  #api-minder          = "https://minder.tado.com/v1"
  #api-energy-insights = "https://energy-insights.tado.com/api"
  #api-energy-bob      = "https://energy-bob.tado.com"
  client-secret       = "wZaRN7rpjn3FoNyF5IFuxg9uMzYJcvOoQ8QWiIqS3hfk6gLhVlG57j5YNoZL2Rtc"
}
