tado4s {
  api-auth       = "https://login.tado.com"
  api-base       = "https://my.tado.com/api/v2"
  http-timeout   = 30 seconds
  max-retries    = 5
  max-retry-time = 1 minute
  ignore-ssl     = false
  client-id      = ${?TADO4S_CLIENT_ID}
}
