tado {
  client-secret  = "wZaRN7rpjn3FoNyF5IFuxg9uMzYJcvOoQ8QWiIqS3hfk6gLhVlG57j5YNoZL2Rtc"
  api-auth       = "https://auth.tado.com"
  api-base       = "https://my.tado.com/api/v2"
  logging-level  = debug
  max-retries    = 3
  max-retry-time = 1 minute
}
