tado4s {
  api-auth                   = "https://login.tado.com"
  api-base                   = "https://my.tado.com/api/v2"
  api-client-id              = ${?TADO4S_CLIENT_ID}
  token-path                 = ~/.tado4s/token.conf
  http-timeout               = 30 seconds
  http-retries-max           = 5
  http-retry-time-max        = 1 minute
  ignore-ssl                 = false
  streaming-concurrency-max  = 4
}
