addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"              % "0.14.7")
addSbtPlugin("com.github.cb372" % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("com.github.sbt"   % "sbt-pgp"                   % "2.3.1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"              % "2.6.1")
addSbtPlugin("org.typelevel"    % "sbt-tpolecat"              % "0.5.6")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"              % "3.12.2")
